### ISSUE TITLE
Running integration and unit tests

### ISSUE THREAD

**Issue by Vinai** [markoshust/magento-docker#41]
Running M2 unit tests is possible via `docker-compose run --rm vendor/bin/phunit -c dev/tests/unit/phpunit.xml.dist`, but running integration tests fails because of three things.

1. `bin/magento` has to be a PHP script as it is called to install and uninstall Magento into a test DB (reference #40)
2. The current working directory has to be `dev/tests/integration`
3. The command line `mysql` and `mysqldump` utilities have to be available because the testing framework uses those to create a dump after the initial install and import that on subsequent runs.

I've fiddled with the mageinferno images to get this working, which it now seems to do.

Solving the issue of `bin/magento` not being a PHP script please refer to #40 

To solve the second and third issue I've done the following (with the help and hand-holding of James Cowie and Anton Siniorg):

Create the file `Docker/integration-test-container/Dockerfile` with the following contents:

```Dockerfile
FROM mageinferno/magento2-php:7.0-fpm-0

MAINTAINER contact@vinaikopp.com

RUN apt-get update

RUN apt-get install -y mysql-client

WORKDIR /var/www/html/dev/tests/integration

ENTRYPOINT ["/usr/local/bin/php", "../../../vendor/bin/phpunit"]

CMD [""]
```

Add this to the `docker-compose.yml` file:

```
integration:
  build: Docker/integration-test-container
  volumes_from:
    - appdata
  links:
    - db

unit:
  image: mageinferno/magento2-php:7.0-fpm-0
  command: php vendor/bin/phpunit -c dev/tests/unit/phpunit.xml.dist
  volumes_from:
    - appdata
```

The `unit` service isn't really required, but I like it because it can be run using `docker-compose run unit` which reads nice.
It also enforces good practice by not linking to the DB since that should not happen in unit tests anyway.

The integration test suite can be run using

```bash
$ docker-compose run --rm integration
```

Because the current working directory is `dev/tests/integration`, individual tests can be started by specifying the path relative to that directory

```bash
$ docker-compose run --rm integration ../../../app/code/Example/Module/Test/Integration`
```
